### PR TITLE
Customize and reorder widgets in Control Center

### PR DESCRIPTION
**Pull request by ErikReider**
- [x] Title widget
- [x] Dnd widget
- [x] Text widget
- [x] Reorder widgets
- [x] Update Man pages
- [x] Update config.json
- [x] Update config JSON schema
- [x] Add default widgets
- [x] Multiple customizations of same widget (ex: "label#about" or "label#desc")

@nwg-piotr How would this affect your shell config?

Fixes: #22

### CODE REVIEW

**Comment by nwg-piotr** [comment]
I need to try and check. Actually I use arguments, leave the swaync config file to users' creativity, so hope it to be all good. Will let you know.

**Comment by nwg-piotr** [comment]
I see no UI elements, just the window and notifications, if any.

image

**Comment by nwg-piotr** [comment]
Sorry, I was wrong (mistaken your work with another one). I use a single config.json file for all my presets, and a separate css file for each of them.

**Comment by nwg-piotr** [comment]
Alright, I'll just add missing config keys from the default config file, if any.

```python
defaults = load_json("/etc/xdg/swaync/config.json")

        for key in defaults:
            if key not in swaync_settings:
                swaync_settings[key] = defaults[key]
```

**Review by nwg-piotr — APPROVED** [review]
I added 4 lines to nwg-shell-config, that will bring swaync back to life after your update. This won't be 100% hassle-free, however: users will have to open nwg-shell-config and press the 'Apply' button.

**Comment by ErikReider** [comment]
> I see no UI elements, just the window and notifications, if any.

Oh. I'll add a few default widgets and fix height not being respected

**Comment by ErikReider** [comment]
> I added 4 lines to nwg-shell-config, that will bring swaync back to life after your update. This won't be 100% hassle-free, however: users will have to open nwg-shell-config and press the 'Apply' button.

Are you referring to the messed up height and missing widgets?

**Comment by nwg-piotr** [comment]
I meant missing widgets, due to missing config keys. If you add default widgets - very well. One way or another, I think I'll leave the default keys check. Your config content may change in the future.

**Comment by ErikReider** [comment]
Oh, the large height was just my config being invalid due to a trailing comma... I'll add default widgets :)

**Comment by nwg-piotr** [comment]
Thank you.

Honestly, the nwg-shell project is already so oversized, that it takes me quite a long time to get back to things I haven't touched recently. Sometimes I can't even remember which application I wrote in Python and which in Go. :)

**Pull request merged**
