### PR TITLE
Add build for fedora and other RPM based distros.

### PR DESCRIPTION
**Pull request by lexa**
I've noticed that his project doesn't have pre-build fedora packages, so I made one.

This pull request adds a [rpkg](https://pagure.io/rpkg) spec teamplate which is used to generate src.rpm and then RPMs for various targets.

As example of results produced by it, there is a copr repo: https://copr.fedorainfracloud.org/coprs/lexa/SwayNotificationCenter/

### CODE REVIEW

**Comment by ErikReider** [comment]
I'm not really sure about how redhats system works but I'm guessing that it'll need to be updated every new release of swaync?

**Comment by lexa** [comment]
Yes, pretty much. As far as I know there is now way to build packages fully automatically when you do new source release.

**Comment by ErikReider** [comment]
In that case you'll need to add that it's an unofficial install source due to my lack of knowledge

**Comment by ErikReider** [comment]
LGTM :)

**Pull request merged**
