### PR TITLE
Add meson_option to build without PulseAudio Widget

### PR DESCRIPTION
**Pull request by ErikReider**
Fixes: #271

`meson build -Dpulse-audio=false` configures it to build without PulseAudio

### CODE REVIEW

**Comment by ErikReider** [comment]
@freijon If this works as expected on your end, I'll merge it :)

**Comment by freijon** [comment]
Hello @ErikReider 

Thanks! I created a test package and the new option works like a charm.
The only thing I notice is that the man-pages still have the the pulse-stuff in them even if built without pulse. I patched that out as well in our package. I'd consider this a bonus goal though ;)

**Comment by ErikReider** [comment]
I'll check if there's a way of patching out sections through meson?

**Comment by ErikReider** [comment]
> The only thing I notice is that the man-pages still have the the pulse-stuff in them even if built without pulse

Added a "hacky" way of doing this. It works like a charm though :)

**Pull request merged**
