### PR TITLE
feat: add urgency level color

### PR DESCRIPTION
**Pull request by cyrinux**
Hey @ErikReider ,

About my issue #94 ,

I success to make something working, maybe not perfect, not sure if I add color on the good part, tell me what you think

image

### CODE REVIEW

**Comment by ErikReider** [comment]
How does it run with notification actions? ie: `notify-send.sh "Summary" "Body" -i "address-book-new" -o "action 1:echo 'action 1'" -o "action 2:echo 'action 2'"`

**Comment by cyrinux** [comment]
Like this 
image

**Review by ErikReider — CHANGES_REQUESTED** [review]

**Review by ErikReider — APPROVED** [review]
LGTM :)

**Comment by cyrinux** [comment]
Thanks you !

**Comment by blastrock** [comment]
Hello,

What happened to this feature? I see that there are no more rules for that in the css https://github.com/ErikReider/SwayNotificationCenter/blob/f55b433e05bf2f7d9772b86a9f613571efc3ae34/data/style/style.scss#L75-L83

Is there a reason this was removed?

**Pull request merged**
