### PR TITLE
build: add fedora build script

### PR DESCRIPTION
**Pull request by ldelossa**
Add a built script for fedora

Signed-off-by: ldelossa <louis.delos@gmail.com>

### CODE REVIEW

**Comment by ErikReider** [comment]
Does this ingrate well with the default package manager? if not, updating could cause compatibility issues in the future

**Comment by ldelossa** [comment]
DNF is fedora's default package manager. All packages needed to build are present in the default repository.

**Comment by ErikReider** [comment]
What I meant is if swaync will show up as installed in dnf

**Comment by ErikReider** [comment]
Hmm. On Arch we have this package in the AUR which integrates very well with pacman (the default package manager) so uninstalling a package like libhandy won't work without uninstalling swaync.

Does dnf support building a local rpkg? That could be a better and safer solution

**Comment by ldelossa** [comment]
Ohh I see, I was under the impression swaync was statically compiled. I see your point, you'd like to link any runtime depedencies to swaync, so if one is removed, you'd be warned its used by swaync?

**Comment by ldelossa** [comment]
Okay cool, not sure if dnf offers anything like this outside of just building an RPM, but I can take a look.

**Comment by ErikReider** [comment]
Hmm. Just remembered that every dependency should be statically linked

**Comment by ldelossa** [comment]
If that is the case, you could remove all dependencies once the binary is built, right? The script begins to make more sense then. 

Originally I wanted to build swaync in a container, which just built the binary and dumped it to the host machine. However, meson is still required to do the actual install part. Not being able to fully encapsulate all the dependencies in the container itself made me abandon that and just push the script

**Comment by ErikReider** [comment]
What happens if you uninstall all of those dependencies after `meson install`? Does it even run?

**Comment by ldelossa** [comment]
Not sure. If meson uses anything like pkg-config to see if libs are avail, should fail,

**Comment by ErikReider** [comment]
> Not sure. If meson uses anything like pkg-config to see if libs are avail, should fail,

If swaync launches without any errors after uninstalling those dependencies, I'll merge this :)

**Comment by mcepl** [comment]
Is it really good idea? The main point of all those `*.spec` files, `debian/*` directories, etc. is that they should provide only the distro-specific information. Why to maintain it upstream, when the proper SPEC file for Fedora (and yes, I could add one for openSUSE as well) will be maintained in https://src.fedoraproject.org/ anyway?

**Comment by ldelossa** [comment]
I only made this as a stop gap because the copr repo trailed behind HEAD pretty far at the time. I use this for myself to build swaync on my machine. I punted it forward incase it was useful, im not too concerned if this gets merged or not. Ill close it.

**Pull request closed without merging**
