### PR TITLE
Ellipsize and wrap notification body

### PR DESCRIPTION
**Pull request by berbiche**
#33's first commit.

The first commit enables showing an ellipsis when a notification's summary is too long and the body is too long.
It also enables line wrapping for overly long notifications.

image
image

The behavior can be tested with `notify-send "Ellipsis test $(python -c 'print("A"*200)')" "$(python -c 'print("A"*800)')"`.

Unfortunately, the notification window is buggy when line wrapping is enabled and does not expand to the size of the content.
The bug is not present in the notification center.

Line wrapping requires the `lines` property to be set, the maximum amount of lines could be made configurable.

### CODE REVIEW

**Comment by ErikReider** [comment]
This needs some further testing

**Comment by berbiche** [comment]
Link back to a related issue on GNOME's bug tracker: https://gitlab.gnome.org/GNOME/gtk/-/issues/2556

**Comment by ErikReider** [comment]
Very interesting! I'll check this out when I get home from the gym :)

**Comment by ErikReider** [comment]
So does this work?

**Comment by berbiche** [comment]
Update: the notification body is correctly trimmed to the configured number of lines

**Comment by ErikReider** [comment]
This is strange... Seems to work with single line notifications while multi-line notifications don't get wrapped?
```sh
notify-send "Ellipsis test" "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore disputandum putant. Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium d 
oloremque laudantium, totam rem aperiam eaque ipsa, quae laudatur, industria, ne fortitudo quidem, sed ista sequimur, ut sine cura metuque vivamus animumque et corpus, quantum efficere possimus, molestia liberemus. ut enim virtutes, de quibus neque depravate iudicant neque corrupte, nonne ei maximam gratiam h
abere debemus, qui hac exaudita quasi voce naturae sic eam firme graviterque comprehenderit, ut omnes bene sanos ad iustitiam, aequitatem, fidem, neque homini infanti aut inpotenti iniuste facta conducunt, qui n
ec facile efficere possit, quod melius sit, migrare de vita. his rebus instructus semper est in voluptate. neque enim disputari sine reprehensione nec cum istis tantopere pugnare, qui Graeca legere malint, modo legant illa ipsa, ne simulent, et iis quidem non admodum flagitem. re mihi non aeque satisfacit, et quidem locis pluribus. sed quot homines, tot sententiae; falli igitur possumus. Quam ob rem voluptas expetenda, fugiendus dolor sit. sentiri haec putat, ut calere ignem, nivem esse albam.
"
```

**Comment by berbiche** [comment]
Looks like this is introduced by the hack in aa63679

**Comment by ErikReider** [comment]
> ~Looks like this is introduced by the hack in [aa63679](https://github.com/ErikReider/SwayNotificationCenter/commit/aa636790fe802d49739ceeb90d7310f2fabb387b)~
> 
> Edit: I can reproduce the behavior on the master branch. `set_lines` seems to ignore multiline strings?

That's a little strange... This patch should fix it :)

```
diff --git a/src/notification/notification.vala b/src/notification/notification.vala
index cb2b0ec..221c15c 100644
--- a/src/notification/notification.vala
+++ b/src/notification/notification.vala
@@ -41,6 +41,7 @@ namespace SwayNotificationCenter {
 
         private uint timeout_id = 0;
 
+        private int number_of_body_lines = 10;
         public bool is_timed = false;
         public NotifyParams param;
         private NotiDaemon notiDaemon;
@@ -53,7 +54,6 @@ namespace SwayNotificationCenter {
 
         public Notification (NotifyParams param,
                              NotiDaemon notiDaemon) {
-            this.body.set_lines (10);
             build_noti (param, notiDaemon);
         }
 
@@ -67,10 +67,11 @@ namespace SwayNotificationCenter {
             this.timeout_delay = timeout;
             this.timeout_low_delay = timeout_low;
             this.timeout_critical_delay = timeout_critical;
+            this.number_of_body_lines = 5;
 #if HAVE_LATEST_LIBHANDY
             this.carousel.allow_scroll_wheel = false;
 #endif
-            this.body.set_lines (5);
+
             build_noti (param, notiDaemon);
             add_noti_timeout ();
             this.size_allocate.connect (on_size_allocation);
@@ -171,6 +172,14 @@ namespace SwayNotificationCenter {
         private void set_body () {
             string text = param.body ?? "";
 
+            // Limits the size of the notification body
+            string[] text_lines = text.split ("\n");
+            if (text_lines.length > this.number_of_body_lines) {
+                text_lines.resize (this.number_of_body_lines);
+                text = string.joinv ("\n", text_lines) + "...";
+            }
+            this.body.set_lines (this.number_of_body_lines);
+
             // Removes all image tags and adds them to an array
             if (text.length > 0) {
                 try {
```

**Comment by berbiche** [comment]
@ErikReider I updated the PR with your fix :slightly_smiling_face:

**Comment by ErikReider** [comment]
I wonder how the GTK widget will respond if that new line truncation cuts off a Pango tag?

**Comment by ErikReider** [comment]
Fixes: #115

**Comment by ErikReider** [comment]
I might have a solution cooking in the back burner that doesn't involve hacky string splitting! :)

So instead of splitting the string, we let GTK handle the sizing but then we experience this:
image

But if we tell the application window to manually resize to the sum of each notifications heights, we should get a correct height right?

```
diff --git a/src/notiWindow/notiWindow.ui b/src/notiWindow/notiWindow.ui
index 513a87f..2eab4c0 100644
--- a/src/notiWindow/notiWindow.ui
+++ b/src/notiWindow/notiWindow.ui
@@ -20,7 +20,6 @@
         <property name="can-focus">False</property>
         <property name="hscrollbar-policy">never</property>
         <property name="window-placement">top-right</property>
-        <property name="max-content-height">600</property>
         <property name="propagate-natural-height">True</property>
         <child>
           <object class="GtkViewport" id="viewport">
diff --git a/src/notiWindow/notiWindow.vala b/src/notiWindow/notiWindow.vala
index 0ce9b1e..7c7bd5f 100644
--- a/src/notiWindow/notiWindow.vala
+++ b/src/notiWindow/notiWindow.vala
@@ -39,6 +39,9 @@ namespace SwayNotificationCenter {
 
         [GtkChild]
         unowned Gtk.Viewport viewport;
+        [GtkChild]
+        unowned Gtk.ScrolledWindow scrolled_window;
+
         [GtkChild]
         unowned Gtk.Box box;
 
@@ -48,6 +51,9 @@ namespace SwayNotificationCenter {
 
         public bool closed = false;
 
+        private const int max_height = 600;
+        private const int min_height = 60;
+
         public NotificationWindow () {
             if (!GtkLayerShell.is_supported ()) {
                 stderr.printf ("GTKLAYERSHELL IS NOT SUPPORTED!\n");
@@ -59,6 +65,11 @@ namespace SwayNotificationCenter {
             GtkLayerShell.init_for_window (this);
             GtkLayerShell.set_layer (this, GtkLayerShell.Layer.OVERLAY);
             this.set_anchor ();
+
+            // -1 should set it to the content size unless it exceeds max_height
+            scrolled_window.set_min_content_height (-1);
+            scrolled_window.set_max_content_height (max_height);
+
             viewport.size_allocate.connect (size_alloc);
 
             this.default_width = ConfigModel.instance.notification_window_width;
@@ -103,6 +114,30 @@ namespace SwayNotificationCenter {
             }
         }
 
+        /**
+         * Sets the Window height to the sum of all childrens height.
+         * Clamps the value to the const min_height and max_height variables.
+         */
+        public override void adjust_size_request (Gtk.Orientation orientation,
+                                                  ref int minimum_size,
+                                                  ref int natural_size) {
+            // This method gets called for both Vertical and Horizontal orientations
+            if (orientation == Gtk.Orientation.VERTICAL) {
+                int minimum_height = 0;
+                int natural_height = 0;
+                foreach (var child in box.get_children ()) {
+                    int height = child.get_allocated_height ();
+                    minimum_height += height;
+                    natural_height += height;
+                }
+                minimum_size = minimum_height.clamp (min_height, max_height);
+                natural_size = natural_height.clamp (min_height, max_height);
+            }
+            base.adjust_size_request (orientation,
+                                      ref minimum_size,
+                                      ref natural_size);
+        }
+
         private void size_alloc () {
             var adj = viewport.vadjustment;
             double upper = adj.get_upper ();
diff --git a/src/notification/notification.ui b/src/notification/notification.ui
index ca50c3f..f033453 100644
--- a/src/notification/notification.ui
+++ b/src/notification/notification.ui
@@ -142,7 +142,7 @@
                                                 <property name="wrap">True</property>
                                                 <property name="wrap-mode">word-char</property>
                                                 <property name="ellipsize">end</property>
-                                                <property name="lines">1</property>
+                                                <property name="lines">10</property>
                                                 <property name="xalign">0</property>
                                                 <property name="yalign">0</property>
                                                 <style>
diff --git a/src/notification/notification.vala b/src/notification/notification.vala
index 2497f4e..5b061d7 100644
--- a/src/notification/notification.vala
+++ b/src/notification/notification.vala
@@ -53,8 +53,8 @@ namespace SwayNotificationCenter {
 
         public Notification (NotifyParams param,
                              NotiDaemon notiDaemon) {
-            build_noti (param, notiDaemon);
             this.body.set_lines (10);
+            build_noti (param, notiDaemon);
         }
 
         // Called to show a temp notification
@@ -67,6 +67,8 @@ namespace SwayNotificationCenter {
             this.timeout_delay = timeout;
             this.timeout_low_delay = timeout_low;
             this.timeout_critical_delay = timeout_critical;
+
+            this.body.set_lines (5);
             build_noti (param, notiDaemon);
             add_noti_timeout ();
         }
```

What do you think?

**Comment by berbiche** [comment]
This solution is also hackish though less than mine.
Did it resolve the issue on your side?
I can't test this atm because I don't have a Wayland-compatible PC to test this on.

You can push directly to my fork's PR branch.

**Comment by ErikReider** [comment]
> This solution is also hackish though less than mine. Did it resolve the issue on your side?

Yes sir! The issue seems to be that the Window doesn't resize with the ScrolledWindows content, so changing how the window calculates its height fixes the issue :)

> You can push directly to my fork's PR branch.

Oh, didn't know that I could do that. Will do!

**Comment by ErikReider** [comment]
Wait, I think that I misunderstood your code completely! Your solution is soo much easier to the eyes and less hacky than mine!

**Review by ErikReider — APPROVED** [review]
LGTM! Feels good to finally merge this! 😆

**Comment by ErikReider** [comment]
Thanks for the help! :)

**Comment by berbiche** [comment]
Thanks for completing the PR! 👍

**Pull request merged**
