### PR TITLE
Be able to use JSON dictionaries in config

### PR DESCRIPTION
**Pull request by ErikReider**
- [x] Deserialize
- [x] Serialize
- [x] Not break when empty (empty dict and removed entirely)
- [x] Works with config reloads

### CODE REVIEW

**Comment by ErikReider** [comment]
What do you think? @nightly-brew

**Comment by nightly-brew** [comment]
Gee you're fast and more determined than me!
Lemme take a lok first, I wann know how you pulled it!

**Comment by nightly-brew** [comment]
That generic there was smooth!
yep, defenitely a fantastic work, and now I know why it didn't work for me anymore...

I tried late at night to make it work, and in between changes I deleted the node return in the deserialization function. That was driving me mad, but for some reason it wasn't giving me any error .-.

**Comment by ErikReider** [comment]
Aah. Yeah... I experienced that too... Any feedback before I merge? @nightly-brew

**Comment by nightly-brew** [comment]
Not really, I took a quick look before shutting off the laptop but what I saw made sense.

I couldn't verify, but I have the feeling this implementation doesn't work for nested hashtables.
If that's the case, I'd say we only need to avoid using nested dicts.

**Comment by ErikReider** [comment]
> I couldn't verify, but I have the feeling this implementation doesn't work for nested hashtables.
If that's the case, I'd say we only need to avoid using nested dicts.

Yeah, it only checks one level deep

**Comment by nightly-brew** [comment]
Well then, no complaints nor suggestions!
Let's merge, then I'll open a MR for the sound feature later :)

**Pull request merged**
