### PR TITLE
Add MPRIS background blur for app icons

### PR DESCRIPTION
**Pull request by abmantis**

### CODE REVIEW

**Comment by ErikReider** [comment]
Request a review when the PR is ready :)

**Review by ErikReider — CHANGES_REQUESTED** [review]
Thanks for the catch and sorry for the delay! Resolve the merge conflicts and potential linting issues and I'll merge :)

**Comment by abmantis** [comment]
> Thanks for the catch and sorry for the delay! Resolve the merge conflicts and potential linting issues and I'll merge :)

No problem :)
Running the linter made quite a lot of changes to the whole file :/ I hope that is ok.

**Comment by ErikReider** [comment]
> > Thanks for the catch and sorry for the delay! Resolve the merge conflicts and potential linting issues and I'll merge :)
> 
> No problem :)
> Running the linter made quite a lot of changes to the whole file :/ I hope that is ok.

Oh yeah, the formatter is kinda broken... Can you restore back and just fix the lines that the linter is complaining about? One day I'll get to fixing this annoying formatter...

**Comment by abmantis** [comment]
> > > Thanks for the catch and sorry for the delay! Resolve the merge conflicts and potential linting issues and I'll merge :)
> > 
> > 
> > No problem :)
> > Running the linter made quite a lot of changes to the whole file :/ I hope that is ok.
> 
> Oh yeah, the formatter is kinda broken... Can you restore back and just fix the lines that the linter is complaining about? One day I'll get to fixing this annoying formatter...

It is a bit of a pain currently, because it also is not able to format just selected lines (it messes them up).

**Comment by abmantis** [comment]
@ErikReider  can we merge this?

**Review by ErikReider — APPROVED** [review]
LGTM! :)

**Pull request merged**
